Tup#89 Enabling ethereum for old spaces
Coinsence/humhub-modules-ethereum pull request #4
Opened 2019-06-06 03:31 UTC by gdalyy

2019-06-06 10:00 UTC, bumi requested changes
we should only set the current balances for each user and not replicate all historic transaction.... what are your thoughts @haythem96

2019-06-06 10:00 UTC, bumi commented on jobs/MigrateSpace.php
> +                Coin::transferCoin($transactionEvent);
we should not replicate all transfers but only set the balance. 
doing all transfers might lead to lots of transactions and thus costs. Also it is not really needed for old transactions, is it?

2019-06-06 10:05 UTC, haythem96 commented on jobs/MigrateSpace.php
> +                Coin::transferCoin($transactionEvent);
Yeah I think so, it will be better to mint the balances for the users...less transactions

2019-06-07 02:12 UTC, gdalyy commented on jobs/MigrateSpace.php
> +                Coin::transferCoin($transactionEvent);
Okay , i'll implement the call for POST /migrate/space to use only `mint` and not replicate all transfers

2019-06-08 13:02 UTC, haythemsellami approved these changes

2019-06-11 08:36 UTC, bumi approved these changes
looks good to me, from what I can tell.

2019-06-17 10:02 UTC, merged